future: true
permalink: /:title/
url: http://yuantingpeng.github.io
name: YuanTing
author: YuanTing
qq: 
email: yuanting@gmail.com
duoshuo: yuanting
beian: 
cnzz: 
weibo: yuanting
github: yuanting
paginate: 20
highlighter: rouge
truncate: true
about: "小彭(yuanting)"
