future: true
permalink: /:title/
url: http://yuantingpeng.github.io
name: yuantingpeng
author: yuantingpeng
qq: 
email: yuantingpeng@gmail.com
duoshuo: yuantingpeng
beian: 
cnzz: 
weibo: yuantingpeng
github: yuantingpeng
paginate: 20
highlighter: rouge
truncate: true
about: "yuantingpeng"
